### ISSUE TITLE
CRS effects on the calculation of areas

### ISSUE THREAD

**Issue by sevamoo** [tudelft3d/Solar3Dcity#1]
Hi Thanks for the great work. It made my life much easier as a noobie to CityGML. 
I was wondering if the code considers the CRS projection in the calculation of the areas? I see it should be [here](https://github.com/tudelft3d/Solar3Dcity/blob/210278d764122f98f010b036198a9815925bc356/polygon3dmodule.py#L203).

Best
Vahid

**Comment by fbiljecki** [comment]
Hi Vahid, thanks for your interest. It has been a while since I wrote this code, but I don't think that CRS is regarded anywhere in this package. That should not be a big deal though, as nearly all 3D city models are stored in a local system (the only issue I foresee are datasets from the US in which coordinates may be stored rather in feet).

**Comment by sevamoo** [comment]
Thanks for the quick reply. Perhaps, I am missing some basic concepts, but my main question was when we are dealing with a wall for example and in my data, I have some CRS like below if this is going to be consistent still? I believe the second CRS is for the Z dimension and definitely, if I change the *EPSG:2056* to *EPSG:4326* everything should be different. 

    urn:ogc:def:crs:EPSG:2056, crs:EPSG:5728

I understand that this topic might not be directly related to this library. So feel free to close it.

Best
Vahid

**Comment by fbiljecki** [comment]
Oh, got it. If both systems (2D & height) are local systems that are in metres, then there should be no issue since it's Euclidian space. Nearly all datasets I worked with back then are like that. However, with the increasing availability and diversity of datasets, that may not be the case anymore, and I reckon some may have lat, lon for 2D coordinates and height in metres. In that case, I am afraid that this package will not take that into account, and you will have to do coordinate transformation first.
